tienda/apps/productos/urls.py
from django.urls import path
from apps.productos.views import index, infProd, infCat, viewProductos, viewCategorias, nuevoRegistro, editarRegistro
from apps.productos.views import eliminarRegistro, nuevoRegistroC, editarRegistroC, eliminarRegistroC, ventas, viewVentas
from apps.productos.views import agregarCarrito, pagar

app_name= 'productos'
urlpatterns = [
	path('', viewProductos.as_view()),
	path('index', viewProductos.as_view()),
	# path('infProd', infProd),
	# path('infCat', infCat),
	path('infProd', viewProductos.as_view(), name= "listaProductos"),
	path('nuevoRegistro', nuevoRegistro, name= "nuevoRegistro"),
    path('editarRegistro/<id>', editarRegistro, name= "editarRegistro"),
    path('eliminarRegistro/<id>', eliminarRegistro, name= "eliminarRegistro"),

	path('infCat', viewCategorias.as_view(), name = 'listaCategorias'),
	path('nuevoRegistroC', nuevoRegistroC, name= "nuevoRegistroC"),
    path('editarRegistroC/<id>', editarRegistroC, name= "editarRegistroC"),
    path('eliminarRegistroC/<id>', eliminarRegistroC, name= "eliminarRegistroC"),
     path('agregarCarrito/<id>', agregarCarrito, name = "agregarCarrito"),
    path('pagar', pagar, name= "pagar"),
    path('ventas' , viewVentas.as_view(), name = "ventas"),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include ('apps.productos.urls')),
    path('', include ('apps.productos.urls')),
]

tienda/apps/productos/models.py
from django.db import models

# Create your models here.
class categoria(models.Model):
	nombreC=models.CharField(max_length=40)

class producto(models.Model):
	nombreProd = models.CharField(max_length=30)
	descripcion = models.CharField(max_length=70)
	costo = models.CharField(max_length=15)
	disponible = models.BooleanField(default=False)
	existencias = models.IntegerField(default = 0)
	categoria = models.ForeignKey(categoria, null= True, blank = True, on_delete = models.CASCADE)

tienda/apps/productos/forms.py
from django import forms
from apps.productos.models import producto

class ProdForm(forms.ModelForm):
	class Meta:
		model = producto
		fields = [
			#Aqui van los nombres de las variables de nuestra bd
			'nombreProd',
			'descripcion',
			'costo',
			'disponible',
			'categoria',
			'existencias',
		]
		labels = {
			'nombreProd': 'Nombre del producto',
			'descripcion': 'Descripción del producto',
			'costo': 'Costo',
			'disponible' : 'Disponibilidad',
			'categoria' : 'Categoría',
			'existencias': 'Productos en existencia'

		}

		widgets = {
			'nombreProd': forms.TextInput(attrs={'class' : 'form-control'}),
			'descripcion': forms.TextInput(attrs={'class' : 'form-control'}),
			'costo': forms.TextInput(attrs={'class' : 'form-control'}),
			'disponible': forms.TextInput(attrs={'class' : 'form-control'}),
			'categoria': forms.TextInput(attrs={'class' : 'form-control'}),
			'existencias' : forms.TextInput(attrs={'class' : 'form-control'}),
		}

tienda/apps/productos/views.py
from django.shortcuts import render, redirect #aqui importamos redirect
from django.http import HttpResponse
# vamos a importar las listas
from django.views.generic import ListView
from apps.productos.models import producto, categoria
from apps.productos.forms import ProdForm
from apps.productos.forms1 import CatForm
from apps.productos.forms2 import VentaProductoForm

def index(request):
	return HttpResponse("Hola")


def infProd(request):
	contexto = {
		'productos':producto.objects.all()
	}
	return render(request, 'tablas/productos.html', contexto)

def infCat(request):
	contexto = {
		'productos':categoria.objects.all()
	}
	return render(request, 'tablas/categorias.html', contexto)
def ventas(request):
	contexto = {
		'productos':producto.objects.all()
	}
	return render(request, 'tablas/ventas.html', contexto)

def nuevoRegistro(request):
	if request.method == 'POST':
		form = ProdForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect ('productos:listaProductos')
	else:
	#Esto es para generar un nuevo registro
		form = ProdForm()
	return render(request, 'tablas/ProductoFormulario.html', {'form' :form})


def editarRegistro(request, id):
	# traemos el objecto con el id
	Producto = producto.objects.get(id=id)
	if (request.method == 'GET'):
		form = ProdForm(instance = Producto) #creamos formulario a aprtir del objeto
	else:
		form = ProdForm(request.POST, instance = Producto)
		if form.is_valid():
			form.save()
		return redirect('productos:listaProductos')
	return render(request, 'tablas/ProductoFormulario.html', {'form' : form})

def eliminarRegistro(request, id):
	Producto = producto.objects.get(id=id).delete()
	return redirect('productos:listaProductos')

#PARA CATEGORIAS
def nuevoRegistroC(request):
	if request.method == 'POST':
		form = CatForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect ('productos:listaCategorias')
	else:
	#Esto es para generar un nuevo registro
		form = CatForm()
	return render(request, 'tablas/CategoriasFormulario.html', {'form' :form})

def editarRegistroC(request, id):
	# traemos el objecto con el id
	Categoria = categoria.objects.get(id=id)
	if (request.method == 'GET'):
		form = CatForm(instance = Categoria) #creamos formulario a aprtir del objeto
	else:
		form = CatForm(request.POST, instance = Categoria)
		if form.is_valid():
			form.save()
		return redirect('productos:listaCategorias')
	return render(request, 'tablas/CategoriasFormulario.html', {'form' : form})

def eliminarRegistroC(request, id):
	Categoria = categoria.objects.get(id=id).delete()
	return redirect('productos:listaCategorias')

#PARA VENTAS
def agregarCarrito(request, id):
	Producto = producto.objects.get(id=id)
	if (request.method == 'GET'):
		form = VentaProductoForm(instance = Producto)
	return render(request, 'tablas/ventaFormulario.html', {'form': form})

def pagar(request):
	return redirect('productos:ventas')


# Creamos una nueva clase
class viewProductos(ListView):
	model = producto
	template_name = 'tablas/productos.html'

# Otra clase para categorias
class viewCategorias(ListView):
	model = categoria
	#queryset = producto.objects.filter(id= '1')
	template_name = 'tablas/categorias.html'


class viewVentas(ListView):
	model = producto
	template_name = 'tablas/ventas.html'

tienda/templates/base/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %} Tienda {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
	<header>
		   {% block header %}
			{% include 'base/nav.html' %}
			{% endblock %}
	</header>

	<div>
		{% block content %} Estas en la sección: {% endblock %}

	</div>


	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

tienda/templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="#">Tienda</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:listaProductos' %}">Productos</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:listaCategorias' %}">Categorías</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:ventas' %}">Ventas</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

tienda/templates/base/nav1.html
{% load staticfiles %}
<br><h1 style="font-size: 30px; text-align: center;">V E N T A S</h1>
<br>
<br><p>Elige qué tipo de productos quieres comprar</p>
<br>

<ul class="list-group">
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="{% url 'productos:vistaProd' %}">Galletas</a>
    <span class="badge badge-primary badge-pill">14</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="">Frituras</a>
    <span class="badge badge-primary badge-pill">2</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="">Refrescos</a>
    <span class="badge badge-primary badge-pill">1</span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <a href="">Chocolates</a>
    <span class="badge badge-primary badge-pill">1</span>
  </li>
</ul>

tienda/templates/tablas/CategoriasFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}


{% block content %}
<div class="container">
	<div class="row justify-content-md-center"> <!-- para centrar el contenedor -->
		<div class="col-8">	
			<h1>Registrar Categoría</h1>
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<button type="submit" class="btn btn-success">Enviar</button>
			</form>
		</div>
	</div>	
</div>
{% endblock %}

tienda/templates/tablas/ProductoFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}


{% block content %}
<div class="container">
	<div class="row justify-content-md-center"> <!-- para centrar el contenedor -->
		<div class="col-8">	
			<h1>Registrar Producto</h1>
			<form method="POST">
				{% csrf_token %}
				{{form.as_p}}
				<button type="submit" class="btn btn-success">Enviar</button>
			</form>
		</div>
	</div>	
</div>
{% endblock %}

tienda/templates/tablas/categorias.html
{% extends 'base/index.html' %}
{% load staticfiles %}
{% block content %}
<div class="container">
	<a href="{% url 'productos:nuevoRegistroC' %}" class="btn mb-3" >Registrar Categoría</a>
	 {% include 'tablas/informacion1.html' %}
</div> 


{% endblock %}

tienda/templates/tablas/informacion.html
	<!-- Aquí pegamos el código de la pagina de bootstrap que queramos apra nuestra tabla -->
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Id del producto</th>
				<th scope="col">Nombre del producto</th>
				<th scope="col">Descripción</th>
				<th scope="col">Costo</th>
				<th scope="col">Existencias</th>
				<th scope="col">Categoria</th>
				<th scope="col" colspan="2">Acciones</th>
			</tr>
		</thead>
		<tbody>
  	<!-- Iniciamos un ciclo for porque aquí
  		vamos a incluir la información de la BD -->
  		{% for producto in object_list %}
  		<tr>
  			<th scope="row">{{ producto.id }}</th>
  			<td>{{ producto.nombreProd }}</td>
  			<td>{{ producto.descripcion }}</td>
  			<td>{{ producto.costo }}</td>
  			<td>{{ producto.existencias }}</td>
  			<td>{{ producto.categoria.nombreC }}</td>
        <td><a href="{% url 'productos:editarRegistro' producto.id %}" class="btn mb-3">Editar</a></td>
        <td><a href="{% url 'productos:eliminarRegistro' producto.id %}" class="btn mb-3">Borrar</a></td>

  		</tr>
  		{% empty %}
  		<tr>
  			<td>Por el momento no contamos con productos</td>
  		</tr>
  		{% endfor %}
  	</tbody>
  </table>

tienda/templates/tablas/informacion1.html
	<!-- Aquí pegamos el código de la pagina de bootstrap que queramos apra nuestra tabla -->
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Id Categoria</th>
				<th scope="col">Nombre de la categoria</th>
				<th scope="col" colspan="2">Acciones</th>
			</tr>
		</thead>
		<tbody>
  	<!-- Iniciamos un ciclo for porque aquí 
  		vamos a incluir la información de la BD -->
  		{% for categoria in object_list %}
  		<tr>
  			<th scope="row">{{ categoria.id }}</th>
  			<td>{{ categoria.nombreC }}</td>  			
        <td><a href="{% url 'productos:editarRegistroC' categoria.id %}" class="btn mb-3">Editar</a></td>
        <td><a href="{% url 'productos:eliminarRegistroC' categoria.id %}" class="btn mb-3">Eliminar</a></td>
  			
  		</tr>
  		{% empty %}
  		<tr>
  			<td>No hay categorias registradas</td>
  		</tr>
  		{% endfor %}
  	</tbody>
  </table>

tienda/templates/tablas/productos.html
{% extends 'base/index.html' %}
{% load staticfiles %}


{% block content %}
	<div class="container">
		
	<a href="{% url 'productos:nuevoRegistro' %}" class="btn mb-3" >Registrar Producto</a>
	

	{% include 'tablas/informacion.html' %} 
	</div>
{% endblock %}

tienda/templates/tablas/tablaventas.html
  <!-- Aquí pegamos el código de la pagina de bootstrap que queramos apra nuestra tabla -->
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id del producto</th>
        <th scope="col">Nombre del producto</th>
        <th scope="col">Descripción</th>
        <th scope="col">Costo</th>
        <th scope="col">Disponibiles</th>
        <th scope="col">Categoria</th>
        <th scope="col" colspan="2">Acciones</th>
      </tr>
    </thead>
    <tbody>
    <!-- Iniciamos un ciclo for porque aquí
      vamos a incluir la información de la BD -->
      {% for producto in object_list %}
      <tr>
        <th scope="row">{{ producto.id }}</th>
        <td>{{ producto.nombreProd }}</td>
        <td>{{ producto.descripcion }}</td>
        <td>{{ producto.costo }}</td>
        <td>{{ producto.existencias }}</td>
        <td>{{ producto.categoria.nombreC }}</td>
        <td><a href="{% url 'productos:agregarCarrito' producto.id %}" class="btn btn-outline-success">Comprar</a></td>


      </tr>
      {% empty %}
      <tr>
        <td>Por el momento no contamos con productos</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

tienda/templates/tablas/ventaFormulario.html
{% extends 'base/index.html' %}
{% load staticfiles %}



{% block content %}
<div class ='container'>
	<div class="row justify-content-md-center">
		<div class="colum-8">
			<h1>Realizar Venta</h1>
			<form method="GET" href="{% url 'productos:pagar' %}" >
				<script type="text/javascript" src="{% static 'js/total.js' %}"></script>
				{% csrf_token %}
				{{ form.as_p }}
				<label>Num.Productos:</label>
				<input class="form-control" type="number" id="cantidad" name="cantidad" placeholder="cantidad" min="0" onclick="evaluar()">
				<label>Total de compra:</label>
				<input class="form-control" type="text" id="total" name="total" placeholder="total">
				<br>
				<button type ='submit' class="btn btn-outline-success" id="pagar" disabled="false">Pagar</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

tienda/templates/tablas/ventas.html
{% extends 'base/index.html' %}
{% load staticfiles %}


{% block content %}
	<div class="container">

<br><h1 style="font-size: 30px; text-align: center;">V E N T A S</h1>
<br>
<div class="alert alert-info">Elige qué tipo de productos quieres comprar</div>

<br>
	{% include 'tablas/tablaventas.html' %}
{% endblock %}